//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Artan.DLL.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Package
    {
        public int PackageID { get; set; }
        public string PackageTitle { get; set; }
    }
}
