//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Artan.DLL.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Companies
    {
        public int CompanyID { get; set; }
        public string CompanyName { get; set; }
        public string Representative { get; set; }
        public string CompanyType { get; set; }
        public string CollaborationDate { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Mobile { get; set; }
        public string Status { get; set; }
        public string Address { get; set; }
        public byte[] Pic { get; set; }
        public string CreateDate { get; set; }
    }
}
