//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Artan.DLL.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Orders
    {
        public int OrderID { get; set; }
        public string OrderDate { get; set; }
        public string PaymentStatus { get; set; }
        public int ConditionID { get; set; }
        public string ConditionTitle { get; set; }
        public Nullable<int> SenderID { get; set; }
        public string Sender { get; set; }
        public string SenderName { get; set; }
        public string SenderMobile { get; set; }
        public string SenderAddress { get; set; }
        public Nullable<int> ReceiverID { get; set; }
        public string Receiver { get; set; }
        public string ReceiverName { get; set; }
        public string ReceiverMobile { get; set; }
        public string ReceiverAddress { get; set; }
        public int PostID { get; set; }
        public string PostTitle { get; set; }
        public int PackageID { get; set; }
        public string PackageTitle { get; set; }
        public string PaymentType { get; set; }
        public string Weight { get; set; }
        public string Number { get; set; }
        public string ShippingCosts { get; set; }
        public string AdminstrativeCosts { get; set; }
        public string Discount { get; set; }
        public string TotalCost { get; set; }
        public string Description { get; set; }
        public string CreateDate { get; set; }
    }
}
