//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Artan.DLL.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Persons
    {
        public int PersonID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FullName { get; set; }
        public string Gender { get; set; }
        public string BirthDate { get; set; }
        public int EducationID { get; set; }
        public string EducationTitle { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string Condition { get; set; }
        public string Address { get; set; }
        public int PositionID { get; set; }
        public string PositionTitle { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string CreateDate { get; set; }
    }
}
